### ISSUE TITLE
QueryOptions doesn't contain a way to get static methods on a class

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/smoke#23]
Currently in QueryOptions there's no way to get static methods. Suggest adding a `includeStatic` option on QueryOptions.

If this is fixed then the `excludeOverriden` functionality needs to be modified as it just checks the name when looking for overrides. Fix is included in the comments for it.

**Comment by donny-dont** [comment]
Opened per request in #22

**Comment by sigmundch** [comment]
yeah, this actually by design: smoke.query is just for instance methods.  To get static methods we require that you pass the type explicitly, since anyways in Dart it is invalid to dynamically dispatch static methods. In particular:

``` dart
SomeType.foo(); // valid
var x = SomeType;
x.foo; // invalid
```

**Comment by donny-dont** [comment]
If its by design go ahead and close it. It was just something I saw that would break the behavior of `excludeOverriden` so I wanted to note that.

**Comment by sigmundch** [comment]
cool - thanks. I'm glad you brought it up though - it isn't obvious (I also had to look closer into smoke to make sure this was the intended design).
